name: Bindings Tests (Go)
on:
  push:
    paths:
      - bindings/go/**
      - include/whisper.h
  pull_request:
    paths:
      - bindings/go/**
      - include/whisper.h

jobs:
  ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: '^1.23'
      - uses: actions/checkout@v6
      - run: |
          cd bindings/go
          make test
