# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI (Native + dotnet)
permissions:
  contents: read
  checks: write
  security-events: write

on:
   push:
      branches: ["main"]
   pull_request:
      branches: ["main"]
   workflow_dispatch:
      inputs:
         BuildGpuLibs:
            description: 'Enable GPU libraries build and publish'
            required: true
            default: 'false'
   schedule:
     - cron: '40 17 * * 0'

jobs:
   codeql-github-actions:
      uses: ./.github/workflows/codeql-github-actions.yml

   android:
      uses: ./.github/workflows/android-native-build.yml

   macos:
      uses: ./.github/workflows/macos-native-build.yml

   windows:
      uses: ./.github/workflows/windows-native-build.yml
      
   windows-no-avx:
      uses: ./.github/workflows/windows-noavx-native-build.yml

   wasm:
      uses: ./.github/workflows/wasm-native-build.yml

   linux:
      uses: ./.github/workflows/linux-native-build.yml

   linux-no-avx:
      uses: ./.github/workflows/linux-noavx-native-build.yml

   linux-vulkan:
      if: ${{ inputs.BuildGpuLibs == 'true' }}
      uses: ./.github/workflows/linux-vulkan-native-build.yml

   windows-cuda:
      if: ${{ inputs.BuildGpuLibs == 'true' }}
      uses: ./.github/workflows/windows-cuda-native-build.yml

   windows-vulkan:
      if: ${{ inputs.BuildGpuLibs == 'true' }}
      uses: ./.github/workflows/windows-vulkan-native-build.yml

   windows-openvino:
      if: ${{ inputs.BuildGpuLibs == 'true' }}
      uses: ./.github/workflows/windows-openvino-native-build.yml
      
   linux-cuda:
      if: ${{ inputs.BuildGpuLibs == 'true' }}
      uses: ./.github/workflows/linux-cuda-native-build.yml

   linux-openvino:
      if: ${{ inputs.BuildGpuLibs == 'true' }}
      uses: ./.github/workflows/linux-openvino-native-build.yml

   macos-coreml:
      if: ${{ inputs.BuildGpuLibs == 'true' }}
      uses: ./.github/workflows/macos-coreml-native-build.yml

   dotnet-build:
      needs:
         - android
         - macos
         - windows
         - wasm
         - linux
      uses: ./.github/workflows/dotnet.yml
      secrets: inherit

   dotnet-maui-build-and-test:
      needs:
         - android
         - macos
         - windows
         - wasm
         - linux
      uses: ./.github/workflows/dotnet-maui.yml
      secrets: inherit
