# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI (Native + dotnet)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:

  android:
     uses: .github/workflows/android-native-build.yml

  macos:
     uses: .github/workflows/macos-native-build.yml

  windows:
     uses: .github/workflows/windows-native-build.yml

  wasm:
     uses: .github/workflows/wasm-native-build.yml

  linux:
     uses: .github/workflows/linux-native-build.yml

  dotnet-build:
    needs:
     - android
     - macos
     - windows
     - wasm
     - linux
    uses: .github/workflows/dotnet.yml
    
