# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI (Native + dotnet)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  android:
     uses: ./.android-native-build.yml@${{ github.head_ref }}

  macos:
     uses: ./.macos-native-build.yml@${{ github.head_ref }}

  windows:
     uses: ./.windows-native-build.yml@${{ github.head_ref }}

  wasm:
     uses: ./.wasm-native-build.yml@${{ github.head_ref }}

  linux:
     uses: ./.linux-native-build.yml@${{ github.head_ref }}

  dotnet-build:
    needs:
     - android
     - macos
     - windows
     - wasm
     - linux
    uses: ./dotnet.yml@${{ github.head_ref }}
    
