name: Linux Cuda12 Native build

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      BuildConfig:
        required: true
        type: string
        default: 'Release'

jobs:
  native-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install aarch64-linux-gnu-gcc
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu && sudo apt-get install -y g++-aarch64-linux-gnu

      - name: Install gcc-arm-linux-gnueabihf
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf && sudo apt-get install -y g++-arm-linux-gnueabihf

      - name: Install CUDA Toolkit (12.4)
        uses: Jimver/cuda-toolkit@8022558310ea543e35132143092835585f60e628
        with:
          cuda: "12.4.0"

      - name: Build Linux CUDA 12 runtime
        run: |
          set -euo pipefail
          rm -rf runtimes/Whisper.net.Runtime.Cuda.Linux/linux-x64
          make linux_cuda BUILD_TYPE=${{ inputs.BuildConfig }}

      - name: Move CUDA 12 runtime into CUDA12 package folder
        run: |
          set -euo pipefail
          rm -rf runtimes/Whisper.net.Runtime.Cuda12.Linux/linux-x64
          mkdir -p runtimes/Whisper.net.Runtime.Cuda12.Linux
          mv runtimes/Whisper.net.Runtime.Cuda.Linux/linux-x64 \
            runtimes/Whisper.net.Runtime.Cuda12.Linux/linux-x64

      - name: Remove CUDA installer (12.x)
        run: rm -rf cuda_installer-*

      - name: Upload Linux CUDA12 Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-cuda12-build
          path: "runtimes/Whisper.net.Run*/linux-*/*"
          retention-days: 7
