name: Linux Vulkan native build

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      BuildConfig:
        required: true
        type: string
        default: 'Release'

jobs:
  native-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install aarch64-linux-gnu-gcc
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu && sudo apt-get install -y g++-aarch64-linux-gnu

      - name: Install gcc-arm-linux-gnueabihf
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf && sudo apt-get install -y g++-arm-linux-gnueabihf

      - name: Install Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@c25f41106918cde0bf347e6f201277392b3a9e9d
        with:
          vulkan-query-version: 1.4.321.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader, SPIRV-Tools, Glslang
          vulkan-use-cache: true

      - name: Setup Vulkan environment
        run: |
          echo "Setting up Vulkan environment"

          # Find glslc executable
          GLSLC_PATH=$(find $GITHUB_WORKSPACE -name "glslc" -type f 2>/dev/null | head -n 1)

          if [ -n "$GLSLC_PATH" ]; then
            echo "Found glslc at: $GLSLC_PATH"
            VULKAN_BIN_DIR=$(dirname "$GLSLC_PATH")
            echo "Adding to PATH: $VULKAN_BIN_DIR"
            echo "$VULKAN_BIN_DIR" >> $GITHUB_PATH

            # Set VULKAN_SDK environment variable
            VULKAN_SDK_PATH=$(dirname "$VULKAN_BIN_DIR")
            echo "Setting VULKAN_SDK to: $VULKAN_SDK_PATH"
            echo "VULKAN_SDK=$VULKAN_SDK_PATH" >> $GITHUB_ENV
          else
            echo "ERROR: glslc not found!"
            exit 1
          fi

      - name: Verify glslc
        run: |
          echo "Verifying glslc installation"
          glslc --version

      - name: Run linux
        run: |
          make linux_vulkan BUILD_TYPE=${{ inputs.BuildConfig }}

      - name: Upload Linux Vulkan Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-vulkan-build
          path: "runtimes/Whisper.net.Run*/linux-*/*"
          retention-days: 7
