name: Linux Vulkan native build

on:
  pull_request:
    branches: [ "main" ]


jobs:
  build:
  
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.head_ref }}
      
      - name: Install aarch64-linux-gnu-gcc
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu && sudo apt-get install -y g++-aarch64-linux-gnu

      - name: Install gcc-arm-linux-gnueabihf
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf && sudo apt-get install -y g++-arm-linux-gnueabihf

      - name: Install GSLC
        run: |
              wget https://storage.googleapis.com/shaderc/artifacts/prod/graphics_shader_compiler/shaderc/linux/continuous_clang_release/469/20240923-182119/install.tgz
              tar -xzf install.tgz
              sudo cp -r install/* /usr/local/
              rm -rf install install.tgz

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.0.4
        with:
          vulkan_version: 1.3.290.0
          optional_components: com.lunarg.vulkan.vma
          install_runtime: true
          cache: true
          stripdown: true
          
      - name: Run linux
        run: make linux_x64_vulkan
      
      - name: Upload Linux Vulkan Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-linux-build
          path: 'Whisper.net.Run*/linux-*/*'
