name: Linux Vulkan native build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  native-build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.head_ref }}

      - name: Install aarch64-linux-gnu-gcc
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu && sudo apt-get install -y g++-aarch64-linux-gnu

      - name: Install gcc-arm-linux-gnueabihf
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf && sudo apt-get install -y g++-arm-linux-gnueabihf

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.0.4
        with:
          vulkan_version: 1.3.290.0
          optional_components: com.lunarg.vulkan.vma
          install_runtime: true
          cache: true
          stripdown: true

      - name: Set Vulkan variables
        run: |
          echo "$VULKAN_SDK/x86_64/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/build/linux-x64-vulkan/bin" >> $GITHUB_PATH
          
      - name: Run linux
        run: |
          make linux_vulkan

      - name: Upload Linux Vulkan Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-vulkan-build
          path: "runtimes/Whisper.net.Run*/linux-*/*"
          retention-days: 7
