name: Linux Vulkan native build

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      BuildConfig:
        required: true
        type: string
        default: 'Release'

jobs:
  native-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install aarch64-linux-gnu-gcc
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu && sudo apt-get install -y g++-aarch64-linux-gnu

      - name: Install gcc-arm-linux-gnueabihf
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf && sudo apt-get install -y g++-arm-linux-gnueabihf

      - name: Install Vulkan SDK
        run: |
          VULKAN_VERSION="1.4.321.1"

          echo "Installing Vulkan SDK $VULKAN_VERSION..."

          # Download and install Vulkan SDK
          wget -q https://sdk.lunarg.com/sdk/download/$VULKAN_VERSION/linux/vulkansdk-linux-x86_64-$VULKAN_VERSION.tar.xz

          # Extract to a temporary directory
          mkdir -p $HOME/vulkan-sdk
          tar -xf vulkansdk-linux-x86_64-$VULKAN_VERSION.tar.xz -C $HOME/vulkan-sdk

          # Set up environment variables
          VULKAN_SDK_PATH="$HOME/vulkan-sdk/$VULKAN_VERSION/x86_64"

          echo "VULKAN_SDK=$VULKAN_SDK_PATH" >> $GITHUB_ENV
          echo "VK_SDK_PATH=$VULKAN_SDK_PATH" >> $GITHUB_ENV
          echo "PATH=$VULKAN_SDK_PATH/bin:$PATH" >> $GITHUB_ENV
          echo "$VULKAN_SDK_PATH/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=$VULKAN_SDK_PATH/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

          echo "Vulkan SDK installed at: $VULKAN_SDK_PATH"

      - name: Verify Vulkan SDK
        run: |
          echo "Verifying Vulkan SDK installation..."
          echo "VULKAN_SDK: $VULKAN_SDK"

          if [ -f "$VULKAN_SDK/bin/glslc" ]; then
            echo "glslc found at: $VULKAN_SDK/bin/glslc"
            $VULKAN_SDK/bin/glslc --version
          else
            echo "ERROR: glslc not found!"
            exit 1
          fi

      - name: Run linux
        run: |
          make linux_vulkan BUILD_TYPE=${{ inputs.BuildConfig }}

      - name: Upload Linux Vulkan Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-vulkan-build
          path: "runtimes/Whisper.net.Run*/linux-*/*"
          retention-days: 7
