name: Linux Vulkan native build

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      BuildConfig:
        required: true
        type: string
        default: 'Release'

jobs:
  native-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install aarch64-linux-gnu-gcc
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu && sudo apt-get install -y g++-aarch64-linux-gnu

      - name: Install gcc-arm-linux-gnueabihf
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf && sudo apt-get install -y g++-arm-linux-gnueabihf

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@34be64e16c022c7d7dd27231cbb2a895ee3b8bc8
        with:
          vulkan_version: 1.4.321.1
          optional_components: com.lunarg.vulkan.vma
          install_runtime: true
          cache: true
          stripdown: true

      - name: Set Vulkan variables
        run: |
          echo "$VULKAN_SDK/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/build/linux-x64-vulkan/bin" >> $GITHUB_PATH

      - name: Run linux
        run: |
          make linux_vulkan BUILD_TYPE=${{ inputs.BuildConfig }}

      - name: Upload Linux Vulkan Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-vulkan-build
          path: "runtimes/Whisper.net.Run*/linux-*/*"
          retention-days: 7
