name: MacOs CoreML Native build

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:

jobs:
  intel-native-build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.head_ref }}

      - name: Run apple coreml build for x64
        run: make apple_coreml_x64

      - name: Upload Mac Intel Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-coreml-intel-build
          path: |
            runtimes/Whisper.net.Run*/*/*
            runtimes/Whisper.net.Run*/*.metal
          retention-days: 7

  arm-native-build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.head_ref }}

      - name: Run apple coreml build for arm
        run: make apple_coreml_arm

      - name: Upload CoreML Mac Arm Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-coreml-arm-build
          path: |
            runtimes/Whisper.net.Run*/*/*
            runtimes/Whisper.net.Run*/*.metal
          retention-days: 7
