name: Quantize turbo model (temp)

on:
  pull_request:
      branches:
      - main


jobs:
  build:

    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        ref: ${{ github.head_ref }}
    
    - name: Install aarch64-linux-gnu-gcc
      run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu && sudo apt-get install -y g++-aarch64-linux-gnu

    - name: Install gcc-arm-linux-gnueabihf
      run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf && sudo apt-get install -y g++-arm-linux-gnueabihf

    - name: Quantize All
      run: |
            cd whisper.cpp
            make quantize
            wget https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo.bin -O models/ggml-large-v3-turbo.bin
            ./quantize models/ggml-large-v3-turbo.bin models/ggml-large-v3-turbo-q5_0.bin q5_0
            ./quantize models/ggml-large-v3-turbo.bin models/ggml-large-v3-turbo-q5_1.bin q5_1
            ./quantize models/ggml-large-v3-turbo.bin models/ggml-large-v3-turbo-q4_0.bin q4_0
            ./quantize models/ggml-large-v3-turbo.bin models/ggml-large-v3-turbo-q4_1.bin q4_1
            ./quantize models/ggml-large-v3-turbo.bin models/ggml-large-v3-turbo-q8_0.bin q8_0


    - name: Upload Quantized Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: quantize-build
        path: 'whisper.cpp/models/*q*.bin'
