name: Windows Cuda12 native build

permissions:
    contents: read

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      BuildConfig:
        required: true
        type: string
        default: 'Release'

jobs:
  native-build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce

      - name: Install OpenCl with vcpkg
        run: |
          vcpkg --triplet=x64-windows install opencl

      - name: Install CUDA Toolkit (12.4)
        uses: Jimver/cuda-toolkit@8022558310ea543e35132143092835585f60e628
        with:
          cuda: "12.4.0"

      - name: Build Windows CUDA 12 runtime
        run: |
          $ErrorActionPreference = "Stop"
          Import-Module ./windows-scripts.ps1
          BuildWindows -Arch "x64" -Cuda $true -Configuration ${{ inputs.BuildConfig }}
        shell: pwsh

      - name: Move CUDA 12 runtime into CUDA12 package folder
        run: |
          $ErrorActionPreference = "Stop"
          if (Test-Path "runtimes/Whisper.net.Runtime.Cuda12.Windows/win-x64") {
            Remove-Item "runtimes/Whisper.net.Runtime.Cuda12.Windows/win-x64" -Recurse -Force
          }
          New-Item -ItemType Directory -Force -Path "runtimes/Whisper.net.Runtime.Cuda12.Windows" | Out-Null
          Move-Item "runtimes/Whisper.net.Runtime.Cuda.Windows/win-x64" \
            "runtimes/Whisper.net.Runtime.Cuda12.Windows/win-x64" -Force
        shell: pwsh

      - name: Remove CUDA installer (12.x)
        run: Remove-Item -Path 'cuda_installer-*' -Recurse -Force -ErrorAction Ignore

      - name: Upload Windows CUDA12 Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-cuda12-build
          path: "runtimes/Whisper.net.Run*/win-*/*"
          retention-days: 7
